# Generated by Django 4.2.3 on 2023-07-27 18:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_de_medida', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('variedad', models.CharField(max_length=50)),
                ('procedencia', models.CharField(max_length=50)),
                ('envase', models.CharField(max_length=50)),
                ('valor_po_kg_mc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tamaño', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=50)),
                ('media_alta', models.CharField(max_length=50)),
                ('media_promedio', models.CharField(max_length=50)),
                ('media_inferior', models.CharField(max_length=50)),
                ('media_alta_pk', models.CharField(max_length=50)),
                ('media_prom_pk', models.CharField(max_length=50)),
                ('media_inferior_pk', models.CharField(max_length=50)),
                ('valor_supermercado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_verduleria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_de_medida', models.CharField(max_length=50)),
                ('cantidad_ajustada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.CharField(max_length=50)),
                ('porciones', models.PositiveIntegerField()),
                ('dificultad', models.CharField(max_length=50)),
                ('tiempo_coccion', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('enlace_video', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ingredientes', models.ManyToManyField(through='recetas.IngredienteReceta', to='recetas.ingrediente')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta'),
        ),
    ]
