# Generated by Django 4.2.3 on 2023-07-31 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingrediente',
            old_name='fecha_actualizacion',
            new_name='fecha_actualizacion_mercado_central',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='fecha_actualizacion_productos',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
