# Generated by Django 4.2.3 on 2023-07-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_alter_ingrediente_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='valor_po_kg_mc',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
