# Generated by Django 4.2.3 on 2023-07-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_alter_ingrediente_valor_po_kg_mc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='media_alta',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='media_alta_pk',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='media_inferior',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='media_inferior_pk',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='media_promedio',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidad_de_medida',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='valor_po_kg_mc',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='valor_supermercado',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='valor_verduleria',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='calidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='envase',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='grado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='media_prom_pk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='procedencia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='tamaño',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='variedad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
