# Generated by Django 4.2.3 on 2023-08-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_alter_ingrediente_calidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='instrucciones',
        ),
        migrations.AlterField(
            model_name='receta',
            name='categoria',
            field=models.CharField(choices=[('TARTA', 'Tartas'), ('CARNES', 'Carnes'), ('SOPAS', 'Sopas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img/recetas'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static/assets/img/videos/'),
        ),
        migrations.CreateModel(
            name='PasoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
        ),
    ]
