# Generated by Django 4.2.3 on 2023-08-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_remove_receta_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientereceta',
            name='unidad_de_medida',
            field=models.CharField(choices=[('gramo', 'gramo'), ('kilo', 'kilo'), ('mililitro', 'mililitro'), ('litro', 'litro'), ('taza', 'taza'), ('cucharadita', 'cucharadita'), ('cucharada', 'cucharada'), ('unidad', 'unidad'), ('unidades', 'unidades'), ('a gusto', 'a gusto'), ('paquete', 'paquete')], max_length=50),
        ),
    ]
