# Generated by Django 4.2.3 on 2023-08-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_alter_ingredientereceta_unidad_de_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='media_prom_pk',
            field=models.FloatField(null=True),
        ),
    ]
